name: Build APK (Self Hosted)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on:
      - self-hosted
      - macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Runner Details
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"
          echo "Hostname: $(hostname)"
          pwd

      - name: Check Flutter
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.${{ github.run_number }}
          name: Release v1.${{ github.run_number }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}